PADDING_SAME = 2
C2D_OFFSET = (PADDING_SAME/2)


IHEIGHT = 1
IWIDTH = 40
ICHANNELS = 1
CNN_CHANNELS = 64

C2D_1_IHEIGHT = (IHEIGHT + PADDING_SAME)
C2D_1_IWIDTH = (IWIDTH + PADDING_SAME)
C2D_1_ICHANNELS = CNN_CHANNELS
C2D_1_KSIZE = 3
C2D_1_BSIZE	= CNN_CHANNELS
C2D_1_OHEIGHT = C2D_1_IHEIGHT
C2D_1_OWIDTH = C2D_1_IWIDTH
C2D_1_OCHANNELS = C2D_1_ICHANNELS